import type { GameMeta, GameCategory } from '@/types/game'

export const GAMES: GameMeta[] = [
  // Single Player Canvas
  { id:'snake',  title:'Snake Evolution', description:'Classic snake with power-ups! Tap D-pad on mobile.', category:'arcade', tags:['arcade','classic','mobile'], badge:'hot', rating:4.9, playCount:1200000, icon:'🐍', bgGradient:['#071a04','#133010'], type:'canvas', controls:[['Arrow/WASD','Move'],['P','Pause'],['R','Restart']], touchControlMode:'dpad' },
  { id:'tetris', title:'Tetris Classic',  description:'Legendary block puzzle. Clear lines to score!',          category:'puzzle', tags:['puzzle','classic'],          badge:'hot', rating:4.8, playCount:980000,  icon:'🧱', bgGradient:['#08081a','#10102a'], type:'canvas', controls:[['← →','Move'],['↑','Rotate'],['Space','Hard Drop']], touchControlMode:'dpad' },
  { id:'2048',   title:'2048',            description:'Slide and merge tiles to reach 2048.',                    category:'puzzle', tags:['puzzle','swipe','mobile'],  badge:'hot', rating:4.7, playCount:874000,  icon:'🔮', bgGradient:['#1a0a00','#3d1500'], type:'canvas', controls:[['Swipe/Arrows','Slide']], touchControlMode:'dpad' },
  { id:'flappy', title:'Flappy Bird',     description:'Tap to fly through pipes. Mobile classic!',               category:'arcade', tags:['arcade','tap','mobile'],    badge:'hot', rating:4.5, playCount:720000,  icon:'🐦', bgGradient:['#001a0a','#003d1a'], type:'canvas', controls:[['Tap/Space','Flap']], touchControlMode:'tap' },
  { id:'space',  title:'Space Shooter',  description:'Blast alien waves with power-ups!',                       category:'shooting',tags:['shooting','space','mobile'],badge:'hot', rating:4.8, playCount:660000,  icon:'🚀', bgGradient:['#000010','#00001a'], type:'canvas', controls:[['← →','Move'],['Space','Shoot']], touchControlMode:'dpad' },
  { id:'breakout',title:'Brick Breaker', description:'Break all bricks with your ball!',                        category:'arcade', tags:['arcade','ball','mobile'],   badge:'new', rating:4.6, playCount:540000,  icon:'🎯', bgGradient:['#1a0000','#2d0000'], type:'canvas', controls:[['Mouse/Drag','Paddle'],['Space','Launch']], touchControlMode:'slide' },
  { id:'memory', title:'Memory Match',   description:'Flip cards and find all matching pairs!',                  category:'puzzle', tags:['puzzle','cards','mobile'],  badge:'new', rating:4.5, playCount:280000,  icon:'🃏', bgGradient:['#0a001a','#1a003d'], type:'canvas', controls:[['Tap/Click','Flip Card']], touchControlMode:'none' },
  { id:'dino',   title:'Dino Run',       description:'Jump cacti, duck pterodactyls! Endless runner.',          category:'retro',  tags:['retro','endless','mobile'], badge:'hot', rating:4.6, playCount:890000,  icon:'🦕', bgGradient:['#1a1a1a','#333333'], type:'canvas', controls:[['Space/Tap','Jump'],['↓/Hold','Duck']], touchControlMode:'tap' },
  { id:'whack',  title:'Whack-a-Mole',  description:'Whack moles before they hide! 60s challenge.',            category:'arcade', tags:['arcade','tap','kids'],      badge:'new', rating:4.4, playCount:195000,  icon:'🔨', bgGradient:['#0a1a00','#183000'], type:'canvas', controls:[['Tap/Click','Whack']], touchControlMode:'none' },
  { id:'tictac', title:'Tic-Tac-Toe AI',description:'X vs O against smart AI. 3 difficulty levels!',          category:'strategy',tags:['strategy','classic'],      badge:''   , rating:4.3, playCount:310000,  icon:'⭕', bgGradient:['#001a1a','#003d3d'], type:'canvas', controls:[['Tap/Click','Place']], touchControlMode:'none' },
  { id:'catch',  title:'Fruit Catcher', description:'Catch fruits, dodge bombs! Mobile-friendly.',             category:'arcade', tags:['arcade','reflex','mobile'], badge:'new', rating:4.5, playCount:167000,  icon:'🍎', bgGradient:['#001a00','#003d00'], type:'canvas', controls:[['Mouse/Drag','Move Basket']], touchControlMode:'slide' },
  { id:'dodge',  title:'Dodge Masters', description:'Dodge bullets as long as possible!',                       category:'action', tags:['action','reflex','mobile'], badge:'new', rating:4.6, playCount:143000,  icon:'💥', bgGradient:['#1a0000','#3d0000'], type:'canvas', controls:[['Drag/Mouse','Move']], touchControlMode:'none' },
  // New games
  { id:'pacman',     title:'Pac-Man Clone',      description:'Full Pac-Man with 4 ghost AI! Power pellets, maze, the works.', category:'retro',  tags:['retro','arcade','classic','mobile'], badge:'new', rating:4.9, playCount:50000, icon:'👾', bgGradient:['#001a1a','#003d3d'], type:'canvas', controls:[['Arrow/WASD','Move'],['P','Pause']], touchControlMode:'dpad', isNew:true },
  { id:'platformer', title:'Pixel Dash',          description:'Side-scrolling platformer with double jump, coins & enemies!', category:'action', tags:['action','platformer','mobile'],       badge:'new', rating:4.8, playCount:35000, icon:'🏃', bgGradient:['#001a0a','#003d20'], type:'canvas', controls:[['A/D or Arrows','Move'],['Space/W','Jump']], touchControlMode:'dpad', isNew:true },
  { id:'solitaire',  title:'Klondike Solitaire',  description:'Classic Solitaire with drag-and-drop cards!',                category:'puzzle', tags:['puzzle','cards','solitaire'],          badge:'new', rating:4.7, playCount:28000, icon:'🎴', bgGradient:['#001a0a','#00400a'], type:'canvas', controls:[['Drag/Click','Move Cards'],['D','Deal']], touchControlMode:'none', isNew:true },
  { id:'bubble',     title:'Bubble Shooter',      description:'Aim and shoot colored bubbles. Match 3 to pop!',             category:'puzzle', tags:['puzzle','match3','mobile'],            badge:'new', rating:4.6, playCount:22000, icon:'🫧', bgGradient:['#001020','#001a40'], type:'canvas', controls:[['Mouse/Tap','Aim & Shoot']], touchControlMode:'none', isNew:true },
  { id:'wordscramble',title:'Word Scramble',      description:'Unscramble words in 60 seconds. +5s per correct!',          category:'puzzle', tags:['puzzle','words','typing'],             badge:'new', rating:4.5, playCount:18000, icon:'📖', bgGradient:['#001a10','#003d25'], type:'canvas', controls:[['Type','Enter word'],['Enter','Submit']], touchControlMode:'none', isNew:true },
  // 2-Player Local
  { id:'pong',      title:'Pong 2 Player',  description:'Classic 2-player pong on one screen. First to 7!',             category:'sports',  tags:['sports','2player','local'],   badge:'2p',    rating:4.4, playCount:340000, icon:'🏓', bgGradient:['#0a0a0a','#1a1a1a'], type:'canvas', controls:[['W/S','P1'],['↑↓','P2']], touchControlMode:'none', is2P:true },
  { id:'tictac2p',  title:'Tic-Tac-Toe 2P', description:'Pass-and-play Tic-Tac-Toe for 2 players!',                   category:'strategy',tags:['strategy','2player','local'], badge:'2p',    rating:4.3, playCount:220000, icon:'❌', bgGradient:['#001a1a','#003d3d'], type:'canvas', controls:[['Tap/Click','Place']], touchControlMode:'none', is2P:true, hasOnline:true },
  { id:'airhockey', title:'Air Hockey 2P',  description:'Fast air hockey for 2 players on one screen! Score 7.',        category:'sports',  tags:['sports','2player','local'],   badge:'2p',    rating:4.6, playCount:412000, icon:'🏒', bgGradient:['#000a1a','#001a3d'], type:'canvas', controls:[['WASD','P1'],['Arrows','P2']], touchControlMode:'none', is2P:true, hasOnline:true },
  { id:'racing2p',  title:'Racing 2 Players',description:'Side-by-side racing! Avoid walls, outrun opponent.',         category:'racing',  tags:['racing','2player','local'],   badge:'2p',    rating:4.5, playCount:298000, icon:'🏎️',bgGradient:['#1a0800','#3d1800'], type:'canvas', controls:[['WASD','P1'],['Arrows','P2']], touchControlMode:'none', is2P:true, hasOnline:true },
  // Online 2-Player
  { id:'snake2p', title:'Snake Battle Online', description:'Battle a friend online in real-time! Share room code, play anywhere.',   category:'arcade', tags:['arcade','online','2player','mobile'], badge:'online', rating:4.8, playCount:567000, icon:'🐍', bgGradient:['#0a1a00','#143000'], type:'canvas', controls:[['Arrow/WASD','Move'],['🌍 Online','Challenge Friend']], touchControlMode:'dpad', is2P:true, hasOnline:true, supportsMultiplayer:true },
  { id:'pong2p',  title:'Pong Online',         description:'Classic pong against a real friend online! Share room code.',           category:'sports', tags:['sports','online','2player','mobile'],  badge:'online', rating:4.7, playCount:389000, icon:'🏓', bgGradient:['#050505','#101010'], type:'canvas', controls:[['Mouse/Drag','Paddle'],['🌍 Online','Challenge Friend']], touchControlMode:'dpad', is2P:true, hasOnline:true, supportsMultiplayer:true },
  // ─── Classic Western Card Games ────────────────────────────────────────────
  { id:'blackjack',  title:'Blackjack 21',      description:'Beat the dealer to 21! Hit, Stand, Double Down. Chip betting system with streaks.', category:'strategy', tags:['cards','casino','classic','strategy'], badge:'hot', rating:4.8, playCount:85000,  icon:'🃏', bgGradient:['#1a0800','#3d1800'], type:'canvas', controls:[['Click','Bet / Hit / Stand'],['2x','Double Down']], touchControlMode:'none', isNew:true },
  { id:'hearts',     title:'Hearts',             description:'Classic 4-player Hearts! Avoid point cards, shoot the moon. You vs 3 AI opponents.', category:'strategy', tags:['cards','classic','strategy','multiplayer'], badge:'new', rating:4.7, playCount:62000, icon:'♥️', bgGradient:['#1a0010','#3d0025'], type:'canvas', controls:[['Click','Select & Play Card']], touchControlMode:'none', isNew:true },
  { id:'slapjack',   title:'Slap Jack',          description:'Slap the Jack before the computer! Fast reflexes required. Space or tap to slap.',   category:'arcade',   tags:['cards','reflex','quick','mobile'],          badge:'new', rating:4.5, playCount:41000, icon:'✋', bgGradient:['#001a0a','#003d18'], type:'canvas', controls:[['Space/Tap','Slap Jack!']], touchControlMode:'tap', isNew:true },
  { id:'war',        title:'War Card Game',      description:'Classic War! Flip cards, win battles, collect them all. Wars trigger epic showdowns.', category:'arcade',  tags:['cards','classic','luck'],                   badge:'new', rating:4.4, playCount:33000, icon:'⚔️', bgGradient:['#1a1a00','#3d3d00'], type:'canvas', controls:[['Click','Flip Card']], touchControlMode:'none', isNew:true },
  // ─── Arab / Middle Eastern Card Games (like Jawaker) ────────────────────────
  { id:'trix',       title:'Trix',               description:'The most popular Arab card game! 4-player trick-taking with Trix, Diamonds, Ladies & Ltoush kingdoms. You vs 3 AI.', category:'strategy', tags:['cards','arabic','trick-taking','multiplayer','classic'], badge:'hot', rating:4.9, playCount:220000, icon:'♠', bgGradient:['#0a001a','#1a0038'], type:'canvas', controls:[['Click','Play Card'],['Select','Choose Kingdom']], touchControlMode:'none', isNew:true },
  { id:'tarneeb',    title:'Tarneeb',            description:'Classic 2v2 Arab trick-taking! Bid, pick trump, make your contract. Team up vs 3 AI.', category:'strategy', tags:['cards','arabic','trick-taking','teams','trump'], badge:'hot', rating:4.8, playCount:180000, icon:'🃏', bgGradient:['#001020','#002040'], type:'canvas', controls:[['Click','Bid / Play Card']], touchControlMode:'none', isNew:true },
  { id:'baloot',     title:'Baloot',             description:'Saudi Arabia\'s favorite card game! 2v2 with Sun or trump bidding. 32-card deck, strategic team play.', category:'strategy', tags:['cards','arabic','saudi','trick-taking','teams'], badge:'hot', rating:4.9, playCount:250000, icon:'🌟', bgGradient:['#1a0a00','#3d2000'], type:'canvas', controls:[['Click','Bid / Play Card']], touchControlMode:'none', isNew:true },
  { id:'estimation', title:'Estimation',         description:'Bid exactly how many tricks you\'ll take! Spades always trump. 4 players, 13 cards each.', category:'strategy', tags:['cards','arabic','trick-taking','bidding','spades'], badge:'new', rating:4.7, playCount:95000, icon:'🎯', bgGradient:['#001a10','#003d20'], type:'canvas', controls:[['Click','Bid / Play Card']], touchControlMode:'none', isNew:true },
  { id:'basra',      title:'Basra',              description:'Classic Egyptian fishing card game! Capture cards from the table. Basra = instant bonus!', category:'puzzle', tags:['cards','arabic','egyptian','fishing','classic'], badge:'new', rating:4.6, playCount:70000, icon:'🎴', bgGradient:['#1a1000','#3d2800'], type:'canvas', controls:[['Click','Play or Capture Card']], touchControlMode:'none', isNew:true },
  { id:'kout',       title:'Kout Bo 6',          description:'Gulf card game — the 6♥ (Kout) beats everything! 4-player no-trump trick battle.', category:'strategy', tags:['cards','arabic','gulf','trick-taking','kout'], badge:'new', rating:4.6, playCount:58000, icon:'💛', bgGradient:['#1a1500','#3d3000'], type:'canvas', controls:[['Click','Play Card']], touchControlMode:'none', isNew:true },
  { id:'oono',       title:'OONO (UNO)',         description:'The viral OONO card game! Match colors & numbers, use action cards to defeat 3 AI opponents.', category:'arcade', tags:['cards','oono','uno','action','colorful','mobile'], badge:'hot', rating:4.8, playCount:310000, icon:'🔴', bgGradient:['#1a0000','#3d0000'], type:'canvas', controls:[['Click','Play Card'],['Wild','Pick Color']], touchControlMode:'none', isNew:true },
  // ─── Board Games ────────────────────────────────────────────────────────────
  { id:'ludo',       title:'Ludo',               description:'Classic Ludo board game! Roll the dice, race your 4 tokens home, capture opponents!', category:'arcade', tags:['board','classic','dice','mobile','family'], badge:'hot', rating:4.7, playCount:430000, icon:'🎲', bgGradient:['#1a0010','#3d0030'], type:'canvas', controls:[['Click','Roll Dice / Move Token']], touchControlMode:'none', isNew:true },
  { id:'domino',     title:'Domino',             description:'Classic draw domino game! Match tiles, chain them together, empty your hand first.', category:'puzzle', tags:['board','domino','tiles','classic','strategy'], badge:'new', rating:4.5, playCount:85000, icon:'🁣', bgGradient:['#0a0a0a','#1e1e1e'], type:'canvas', controls:[['Click','Select & Place Tile']], touchControlMode:'none', isNew:true },
  { id:'snakes',     title:'Snakes & Ladders',   description:'The timeless dice board game! Climb ladders, avoid snakes, race to 100!', category:'arcade', tags:['board','classic','dice','family','kids'], badge:'new', rating:4.4, playCount:62000, icon:'🐍', bgGradient:['#001a05','#003d10'], type:'canvas', controls:[['Click','Roll Dice']], touchControlMode:'none', isNew:true },
  // Iframe games
  { id:'slither-io',        title:'Slither.io',         description:'Massive online snake — trap opponents, steal their mass!',   category:'multiplayer', tags:['multiplayer','io','online'],   badge:'hot',  rating:4.7, playCount:9100000,  icon:'🐍', bgGradient:['#0a001a','#1a003d'], type:'iframe', iframeUrl:'https://slither.io',                                                controls:[['Mouse','Move'],['Click','Boost']], supportsMultiplayer:true },
  { id:'agar-io',           title:'Agar.io',            description:'Grow your cell by eating smaller ones!',                   category:'multiplayer', tags:['multiplayer','io','online'],   badge:'hot',  rating:4.6, playCount:8400000,  icon:'🔵', bgGradient:['#001a10','#00400a'], type:'iframe', iframeUrl:'https://agar.io',                                                    controls:[['Mouse','Move'],['Space','Split']], supportsMultiplayer:true },
  { id:'minecraft-classic', title:'Minecraft Classic',  description:'The original Minecraft in your browser. Build anything!',  category:'sandbox',     tags:['sandbox','building','classic'],badge:'top',  rating:4.9, playCount:11000000, icon:'⛏️',bgGradient:['#0a1a00','#152e00'], type:'iframe', iframeUrl:'https://classic.minecraft.net',                                      controls:[['WASD','Move'],['Mouse','Build']] },
  { id:'krunker-io',        title:'Krunker.io',         description:'Fast FPS with real players worldwide!',                    category:'shooting',    tags:['shooting','fps','online'],     badge:'hot',  rating:4.7, playCount:5200000,  icon:'🎯', bgGradient:['#1a0000','#3d0000'], type:'iframe', iframeUrl:'https://krunker.io',                                                 controls:[['WASD','Move'],['Mouse','Aim & Shoot']], supportsMultiplayer:true },
  { id:'1v1-lol',           title:'1v1.lol',            description:'Build and shoot in this ultimate 1v1 game!',               category:'shooting',    tags:['shooting','online','1v1'],     badge:'top',  rating:4.7, playCount:4300000,  icon:'🏗️',bgGradient:['#001a1a','#003d3d'], type:'iframe', iframeUrl:'https://1v1.lol',                                                    controls:[['WASD','Move'],['B','Build']], supportsMultiplayer:true },
  { id:'drift-hunters',     title:'Drift Hunters',      description:'Best drift racing in your browser. Tune real cars!',       category:'racing',      tags:['racing','drift','cars'],       badge:'hot',  rating:4.7, playCount:3800000,  icon:'🏎️',bgGradient:['#1a0a00','#3d1500'], type:'iframe', iframeUrl:'https://www.crazygames.com/game/drift-hunters',                      controls:[['WASD','Drive'],['Space','Handbrake']] },
  { id:'moto-x3m',          title:'Moto X3M',           description:'Insane stunt motorcycle racing!',                          category:'racing',      tags:['racing','stunt','bikes'],      badge:'hot',  rating:4.7, playCount:4100000,  icon:'🏍️',bgGradient:['#001a00','#003d00'], type:'iframe', iframeUrl:'https://www.crazygames.com/game/moto-x3m',                           controls:[['← →','Accel/Brake'],['↑↓','Flip']] },
  { id:'geometry-dash',     title:'Geometry Dash',      description:'Jump over obstacles in rhythm. Most addictive ever!',      category:'action',      tags:['action','rhythm','mobile'],    badge:'hot',  rating:4.7, playCount:4800000,  icon:'🔷', bgGradient:['#001a20','#003040'], type:'iframe', iframeUrl:'https://www.crazygames.com/game/geometry-dash-classic',              controls:[['Tap/Space','Jump']] },
  { id:'stumble-guys',      title:'Stumble Guys',       description:'Chaotic 32-player obstacle race online!',                  category:'multiplayer', tags:['multiplayer','party','online'],badge:'new',  rating:4.6, playCount:2100000,  icon:'🫘', bgGradient:['#200010','#40002a'], type:'iframe', iframeUrl:'https://www.crazygames.com/game/stumble-guys',                       controls:[['WASD','Move'],['Space','Jump']], supportsMultiplayer:true },
  { id:'wordle',            title:'Wordle',             description:'Guess the 5-letter word in 6 tries. Daily puzzle!',        category:'puzzle',      tags:['puzzle','words','daily'],      badge:'top',  rating:4.8, playCount:6700000,  icon:'📝', bgGradient:['#001a10','#003d25'], type:'iframe', iframeUrl:'https://www.nytimes.com/games/wordle/index.html',                   controls:[['Type & Enter','Guess']] },
  { id:'chess-online',      title:'Chess Online',       description:'Play chess vs AI or real players online!',                 category:'strategy',    tags:['strategy','chess','online'],   badge:'top',  rating:4.9, playCount:2100000,  icon:'♟️', bgGradient:['#1a1200','#3d2b00'], type:'iframe', iframeUrl:'https://www.chess.com/play/computer',                              controls:[['Click','Move Piece']], supportsMultiplayer:true },
  { id:'skribbl-io',        title:'Skribbl.io',         description:'Draw and guess with friends online! Multiplayer Pictionary.', category:'multiplayer', tags:['multiplayer','drawing','online'], badge:'new', rating:4.6, playCount:1800000, icon:'🎨', bgGradient:['#001a0a','#003d12'], type:'iframe', iframeUrl:'https://skribbl.io', controls:[['Mouse','Draw'],['Type','Guess']], supportsMultiplayer:true },
  { id:'paper-io',          title:'Paper.io 2',         description:'Capture territory and eliminate players worldwide!',       category:'multiplayer', tags:['multiplayer','io','online'],   badge:''   , rating:4.5, playCount:3200000,  icon:'📄', bgGradient:['#1a1a00','#3d3d00'], type:'iframe', iframeUrl:'https://paper-io.com',                                               controls:[['Arrows/WASD','Move']], supportsMultiplayer:true },
  { id:'minesweeper',       title:'Minesweeper',        description:'Classic minesweeper. Find all mines!',                    category:'puzzle',      tags:['puzzle','classic','strategy'], badge:''   , rating:4.5, playCount:1300000,  icon:'💣', bgGradient:['#0a0a0a','#1a1a1a'], type:'iframe', iframeUrl:'https://minesweeper.online',                                         controls:[['Click','Reveal'],['Right Click','Flag']] },
  { id:'rocket-soccer',     title:'Rocket Soccer Derby', description:'Soccer with rocket-powered cars!',                       category:'sports',      tags:['sports','racing','online'],    badge:'hot',  rating:4.7, playCount:2300000,  icon:'🚗', bgGradient:['#1a0a00','#3d1500'], type:'iframe', iframeUrl:'https://www.crazygames.com/game/rocket-soccer-derby',                controls:[['← →','Move'],['↑','Boost']] },
]

export interface CategoryInfo { id: string; label: string; icon: string; count: number }

export const CATEGORIES: CategoryInfo[] = [
  { id:'all',         label:'All Games',          icon:'🕹️', count:GAMES.length },
  { id:'cards',       label:'Card Games',         icon:'🃏', count:GAMES.filter(g=>g.tags.includes('cards')).length },
  { id:'arabic',      label:'Arab Games',         icon:'🌙', count:GAMES.filter(g=>g.tags.includes('arabic')).length },
  { id:'board',       label:'Board Games',        icon:'🎲', count:GAMES.filter(g=>g.tags.includes('board')).length },
  { id:'arcade',      label:'Arcade',             icon:'🕹️', count:GAMES.filter(g=>g.category==='arcade').length },
  { id:'puzzle',      label:'Puzzle',             icon:'🧩', count:GAMES.filter(g=>g.category==='puzzle').length },
  { id:'action',      label:'Action',             icon:'⚔️', count:GAMES.filter(g=>g.category==='action').length },
  { id:'strategy',    label:'Strategy',           icon:'♟️', count:GAMES.filter(g=>g.category==='strategy').length },
  { id:'racing',      label:'Racing',             icon:'🏎️', count:GAMES.filter(g=>g.category==='racing').length },
  { id:'sports',      label:'Sports',             icon:'⚽', count:GAMES.filter(g=>g.category==='sports').length },
  { id:'shooting',    label:'Shooting',           icon:'🎯', count:GAMES.filter(g=>g.category==='shooting').length },
  { id:'multiplayer', label:'Online Multiplayer', icon:'🌍', count:GAMES.filter(g=>g.category==='multiplayer'||g.supportsMultiplayer).length },
  { id:'2player',     label:'2-Player',           icon:'👥', count:GAMES.filter(g=>g.is2P||g.hasOnline).length },
  { id:'retro',       label:'Retro',              icon:'👾', count:GAMES.filter(g=>g.category==='retro').length },
  { id:'sandbox',     label:'Sandbox',            icon:'⛏️', count:GAMES.filter(g=>g.category==='sandbox').length },
]

export function getGame(id: string) { return GAMES.find(g => g.id === id) }

export function getGamesByCategory(category: string): GameMeta[] {
  if (category === 'all') return GAMES
  if (category === '2player') return GAMES.filter(g => g.is2P || g.hasOnline)
  if (category === 'multiplayer') return GAMES.filter(g => g.category === 'multiplayer' || g.supportsMultiplayer)
  if (category === 'cards') return GAMES.filter(g => g.tags.includes('cards'))
  if (category === 'arabic') return GAMES.filter(g => g.tags.includes('arabic'))
  if (category === 'board') return GAMES.filter(g => g.tags.includes('board'))
  return GAMES.filter(g => g.category === (category as GameCategory) || g.tags.includes(category))
}

export function getRelatedGames(game: GameMeta, count = 8): GameMeta[] {
  return GAMES
    .filter(g => g.id !== game.id && (g.category === game.category || g.tags.some(t => game.tags.includes(t))))
    .slice(0, count)
}
